[Settings]
#translation_file = language-packages/1/TOP 25 Phrases You Need in Italian.txt
#translation_file = language-packages/test-italian.txt
translation_file = language-packages/1/thank-you-excuse-me.txt
audio_folder = language-packages/audio
audio_extension = mp3
language = it
separator =  : 
repeat = 3
reverse_repeat = 4