[Settings]
#deck_file = decks/1/TOP 25 Phrases You Need in Italian.txt
#deck_file = decks/test-italian.txt
deck_file = 'decks/2/test.txt'
audio_folder = 'decks/audio'
audio_extension = 'mp3'
language = 'it'
separator = ' : '
repeat = 3
reverse_repeat = 4